class Sprites:
    SNAKE_HEAD = "sprites/head.png"
    SNAKE_BODY = "sprites/body.png"
    SNAKE_TAIL = "sprites/tail.png"
    SNAKE_TURN = "sprites/turn.png"
    BACKGROUND = "sprites/grassSprite.png"
    BACKGROUND_MENU = "sprites/background_menu.png"
    ICON = "sprites/SnakeIcon.png"
    FOOD = "sprites/FoodApple.png"
    FON = "sprites/fon.png"
    BUTTON_START = "sprites/button_start.png"
    BUTTON_OPTIONS = "sprites/button_options.png"
    BUTTON_EXIT = "sprites/button_exit.png"
